---
- name: Install db and web package
  yum:
    name:
      - "{{ ansible_local.custom.packages.db_package }}"
      - "{{ ansible_local.custom.packages.web_package }}"
    state: latest

- name: Start and enable db server
  service:
    name: "{{ ansible_local.custom.services.db_service }}"
    state: started
    enabled: true


- name: Start and enable web server
  service:
    name: "{{ ansible_local.custom.services.web_service }}"
    state: started
    enabled: true
...
