---
# This setup playbook will deploy smb, ftp, db, and web services on specified goup of hosts

- hosts: all
  vars:
    firewall: firewalld
  tasks:
    - name: Install firewall
      yum:
        name: "{{ firewall }}"
        state: latest

    - name: Start firewall service
      service:
        name: "{{ firewall }}"
        state: started
        enabled: true

- hosts: lamp
  tasks:
    - name: Include vars from vars/allvars.yml file
      include_vars: vars/allvars.yml

    - name: Load and execute the tasks from ./tasks/lamp_tasks.yml file
      include: tasks/lamp_tasks.yml

    - name: Open the port for web server
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled

    - name: Create index.html file
      copy:
        content: "{{ ansible_fqdn }}({{ ansible_default_ipv4.address }} managed by Ansible\n"
        dest: "{{ web_root }}/index.html"

- hosts: file
  tasks:
    - name: Include vars from vars/allvars.yml file
      include_vars: vars/allvars.yml

    - name: Load and execute the tasks from ./tasks/file_tasks.yml file
      include: tasks/file_tasks.yml

    - name: Open the port for smb server
      firewalld:
        service: samba
        permanent: true
        immediate: true
        state: enabled

    - name: Open the port for ftp server
      firewalld:
        service: ftp
        permanent: true
        immediate: true
        state: enabled
...
